Repository openivity/openivity.github.io, pull requests merged in 2023-12, with the labels that each got.

#50 feat: implement encoding to fit
  package-lock.json
  package.json
  src/assets/main.scss
  src/assets/tools.scss
  src/assets/v-select.scss
  src/components/AreaGraph.vue
  src/components/ElevationGraph.vue
  src/components/OpenActivity.vue
  src/components/TheTools.vue
  src/components/ToolDeviceSelector.vue
  src/components/ToolFieldsRemover.vue
  src/components/ToolModeSelector.vue
  src/components/ToolSportChanger.vue
  src/components/ToolTrackpointsConcealer.vue
  src/components/ToolTrackpointsSlider.vue
  src/components/ToolTrackpointsTrimmer.vue
  src/main.ts
  src/spec/activity-service.ts
  src/wasm/activity-service/accumulator/accumulator.go
  src/wasm/activity-service/activity/activity.go
  src/wasm/activity-service/activity/creator.go
  src/wasm/activity-service/activity/event.go
  src/wasm/activity-service/activity/fit/activity.go
  src/wasm/activity-service/activity/fit/creator.go
  src/wasm/activity-service/activity/fit/event.go
  src/wasm/activity-service/activity/fit/lap.go
  src/wasm/activity-service/activity/fit/manufacturer.go
  src/wasm/activity-service/activity/fit/record.go
  src/wasm/activity-service/activity/fit/service.go
  src/wasm/activity-service/activity/fit/session.go
  src/wasm/activity-service/activity/gpx/record.go
  src/wasm/activity-service/activity/gpx/service.go
  src/wasm/activity-service/activity/lap.go
  src/wasm/activity-service/activity/record.go
  src/wasm/activity-service/activity/service.go
  src/wasm/activity-service/activity/session.go
  src/wasm/activity-service/activity/tcx/record.go
  src/wasm/activity-service/activity/tcx/schema/tcx_test.go.bak
  src/wasm/activity-service/activity/tcx/service.go
  src/wasm/activity-service/go.mod
  src/wasm/activity-service/go.sum
  src/wasm/activity-service/kit/kit.go
  src/wasm/activity-service/main.go
  src/wasm/activity-service/manufacturers.json
  src/wasm/activity-service/preprocessor/preprocessor.go
  src/wasm/activity-service/scale/scale.go
  src/wasm/activity-service/service/result/encode.go
  src/wasm/activity-service/service/result/manufacturer_list.go
  src/wasm/activity-service/service/result/sport_list.go
  src/wasm/activity-service/service/service.go
  src/wasm/activity-service/service/spec/encode.go
  src/wasm/activity-service/service/spec/filetype.go
  src/workers/activity-service.ts
  src/workers/wasm-services.ts
Labels: bug, enhancement

#60 feat: add WorkoutType field in Session, and ToleranceMovingSpeed in Sport
  src/spec/activity-service.ts
  src/spec/activity.ts
  src/wasm/activity-service/activity/fit/service.go
  src/wasm/activity-service/activity/gpx/service.go
  src/wasm/activity-service/activity/session.go
  src/wasm/activity-service/activity/tcx/service.go
  src/wasm/activity-service/activity/util.go
  src/wasm/activity-service/preprocessor/preprocessor.go
  src/wasm/activity-service/service/result/sport_list.go
  src/wasm/activity-service/service/service.go
Labels: enhancement

#65 Split pace last data invalid with invalid record + Support Multisession
  src/components/SplitPaceGraph.vue
Labels: bug, enhancement

#64 fix: hr-zone label alignment
  src/components/HeartRateZoneBar.vue
Labels: bug

#66 fix: restyling graph components
  src/components/AreaGraph.vue
  src/components/ElevationGraph.vue
  src/components/OpenActivity.vue
Labels: UI

#69 fix: total ascent/descent and total elapsed/moving time calculation
  src/wasm/activity-service/activity/lap.go
Labels: bug

#71 fix (#55): combine activity should combine last session and first session of the corresponding activities
  src/components/ToolModeSelector.vue
  src/wasm/activity-service/activity/fit/listener.go
  src/wasm/activity-service/activity/fit/session.go
  src/wasm/activity-service/service/service.go
Labels: bug

#70 fix (#62): tool's trim/conceal negative distance
  src/components/ToolTrackpointsSlider.vue
  src/wasm/activity-service/activity/fit/service.go
Labels: bug

#75 fix (#73): handling null altitude, instead of treat as 0, make it minDomain
  src/components/AreaGraph.vue
  src/components/ElevationGraph.vue
Labels: bug

#76 chore: bump FIT SDK for Go version from v0.1.5 to v0.2.0
  src/wasm/activity-service/go.mod
  src/wasm/activity-service/go.sum
Labels: chore

#77 feat(#72): implement GPX and TCX encoding
  src/assets/v-select.scss
  src/components/OpenActivity.vue
  src/components/TheTools.vue
  src/components/ToolDeviceNameInput.vue
  src/components/ToolDeviceSelector.vue
  src/components/ToolFileTypeSelector.vue
  src/wasm/activity-service/activity/fit/service.go
  src/wasm/activity-service/activity/gpx/schema/extensions.go
  src/wasm/activity-service/activity/gpx/schema/gpx.go
  src/wasm/activity-service/activity/gpx/schema/metadata.go
  src/wasm/activity-service/activity/gpx/schema/track.go
  src/wasm/activity-service/activity/gpx/service.go
  src/wasm/activity-service/activity/lap.go
  src/wasm/activity-service/activity/tcx/schema/activity.go
  src/wasm/activity-service/activity/tcx/schema/author.go
  src/wasm/activity-service/activity/tcx/schema/lap.go
  src/wasm/activity-service/activity/tcx/schema/tcx.go
  src/wasm/activity-service/activity/tcx/schema/tcx_test.go.bak
  src/wasm/activity-service/activity/tcx/schema/track.go
  src/wasm/activity-service/activity/tcx/service.go
  src/wasm/activity-service/kit/xml/xml.go
  src/wasm/activity-service/service/service.go
Labels: bug, enhancement

#81 chore: bump fit sdk version from 0.2.0 to 0.3.1
  src/wasm/activity-service/go.mod
  src/wasm/activity-service/go.sum
Labels: chore

#79 fix(no ticket): device mapping for tcx
  src/wasm/activity-service/activity/tcx/service.go
Labels: bug, WebAssembly

#80 fix(no ticket): device mapping selection
  src/components/TheTools.vue
  src/components/ToolDeviceNameInput.vue
  src/components/ToolDeviceSelector.vue
  src/components/ToolSportChanger.vue
Labels: bug, enhancement, UI

#83 perf(no-ticket): reduce interop bottleneck
  src/wasm/activity-service/activity/activity.go
  src/wasm/activity-service/activity/buffer_pool.go
  src/wasm/activity-service/activity/creator.go
  src/wasm/activity-service/activity/fit/creator.go
  src/wasm/activity-service/activity/fit/service.go
  src/wasm/activity-service/activity/fit/timezone.go
  src/wasm/activity-service/activity/lap.go
  src/wasm/activity-service/activity/record.go
  src/wasm/activity-service/activity/session.go
  src/wasm/activity-service/go.mod
  src/wasm/activity-service/go.sum
  src/wasm/activity-service/main.go
  src/wasm/activity-service/service/result/decode.go
  src/wasm/activity-service/service/result/encode.go
  src/wasm/activity-service/service/result/manufacturer_list.go
  src/wasm/activity-service/service/result/sport_list.go
  src/workers/activity-service.ts
Labels: enhancement

#87 chore: bump FIT SDK version to v0.5.0
  src/wasm/activity-service/go.mod
  src/wasm/activity-service/go.sum
Labels: chore
