Repository openivity/openivity.github.io, pull requests merged in 2023-11, with the labels that each got.

#19 feat: new experiment layout, add elev and basic graphs
  package-lock.json
  package.json
  src/assets/main.scss
  src/components/AreaGraph.vue
  src/components/CadenceGraph.vue
  src/components/ElevationGraph.vue
  src/components/HeartRateGraph.vue
  src/components/Loading.vue
  src/components/PowerGraph.vue
  src/components/SpeedGraph.vue
  src/components/TemperatureGraph.vue
  src/components/TheActivity.vue
  src/components/TheMap.vue
  src/components/TheNavigatorInput.vue
  src/components/TheSummary.vue
  src/components/v0/TheActivity.vue
  src/main.ts
  src/router/index.ts
  src/toolkit/date.ts
  src/views/example/ElevationGraphView.vue
  src/views/v0/ActivityView.vue
  src/wasm/fitsvc/activity/geojson.go
  src/wasm/fitsvc/activity/listener.go
  src/wasm/fitsvc/activity/service.go
Labels: enhancement

#24 fix: ui/ux, distance calculation on combined record
  index.html
  package-lock.json
  package.json
  src/assets/bootstrap.scss
  src/assets/main.scss
  src/components/AreaGraph.vue
  src/components/ElevationGraph.vue
  src/components/OpenActivity.vue
  src/components/PowerGraph.vue
  src/components/TheActivity.vue
  src/components/TheLap.vue
  src/components/TheLoading.vue
  src/components/TheMap.vue
  src/components/TheNavigator.vue
  src/components/TheSession.vue
  src/components/TheSummary.vue
  src/main.ts
  src/router/index.ts
  src/spec/activity.ts
  src/toolkit/date.ts
  src/views/OpenActivityView.vue
  src/views/v0/ActivityView.vue
  src/wasm/fitsvc/activity/activity.go
  src/wasm/fitsvc/activity/listener.go
  src/wasm/fitsvc/activity/service.go
  src/wasm/fitsvc/go.mod
  src/wasm/fitsvc/go.sum
Labels: bug, enhancement

#25 fix: area graph pointer
  src/components/AreaGraph.vue
Labels: bug

#31 fix: trigger render and css style
  src/components/ElevationGraph.vue
  src/components/OpenActivity.vue
  src/components/TheLoading.vue
Labels: bug

#32 feat: clustering map features for fast lookup
  src/assets/scrollbar.scss
  src/components/OpenActivity.vue
  src/components/TheMap.vue
  src/components/legacy/TheActivity.vue
Labels: enhancement

#33 Implement Find Nearest on Map Hover using KDTree and as optional (dropdown)
  package-lock.json
  package.json
  src/@types/geokdbush-tk/index.d.ts
  src/components/TheMap.vue
Labels: enhancement

#34 Seamless switch between Standard to KDTree after indexed #33
  src/components/TheMap.vue
Labels: enhancement

#36 fix: reduce reactivity to improve performance
  package-lock.json
  package.json
  src/components/OpenActivity.vue
  src/components/TheMap.vue
Labels: enhancement

#39 feat: add route-line outline color
  src/components/TheMap.vue
Labels: enhancement, UI

#38 feat: Implement decoding TCX file
  src/components/OpenActivity.vue
  src/wasm/activity-service/activity/creator.go
  src/wasm/activity-service/activity/fit/listener.go
  src/wasm/activity-service/activity/gpx/record.go
  src/wasm/activity-service/activity/gpx/service.go
  src/wasm/activity-service/activity/lap.go
  src/wasm/activity-service/activity/record.go
  src/wasm/activity-service/activity/session.go
  src/wasm/activity-service/activity/tcx/record.go
  src/wasm/activity-service/activity/tcx/schema/activity.go
  src/wasm/activity-service/activity/tcx/schema/author.go
  src/wasm/activity-service/activity/tcx/schema/lap.go
  src/wasm/activity-service/activity/tcx/schema/tcx.go
  src/wasm/activity-service/activity/tcx/schema/track.go
  src/wasm/activity-service/activity/tcx/service.go
  src/wasm/activity-service/activity/util.go
  src/wasm/activity-service/preprocessor/preprocessor.go
Labels: enhancement, WebAssembly

#40 fix: standarize sports
  src/components/OpenActivity.vue
  src/spec/activity.ts
  src/wasm/activity-service/activity/fit/listener.go
  src/wasm/activity-service/activity/fit/session.go
  src/wasm/activity-service/activity/gpx/service.go
  src/wasm/activity-service/activity/session.go
  src/wasm/activity-service/activity/tcx/service.go
  src/wasm/activity-service/activity/util.go
Labels: bug

#42 fix: fit service logic
  src/components/OpenActivity.vue
  src/components/TheSummary.vue
  src/wasm/activity-service/activity/fit/lap.go
  src/wasm/activity-service/activity/fit/listener.go
  src/wasm/activity-service/activity/fit/service.go
  src/wasm/activity-service/activity/gpx/service.go
  src/wasm/activity-service/activity/lap.go
  src/wasm/activity-service/activity/service.go
  src/wasm/activity-service/activity/session.go
  src/wasm/activity-service/activity/tcx/service.go
  src/wasm/activity-service/activity/util.go
  src/wasm/activity-service/kit/kit.go
  src/wasm/activity-service/preprocessor/preprocessor.go
Labels: bug

#45 chore: add serialization elapsed and total elapsed
  src/components/OpenActivity.vue
  src/wasm/activity-service/service/result.go
  src/wasm/activity-service/service/service.go
Labels: chore

#43 feat: enable graph by timestamp when there is no distance
  src/components/AreaGraph.vue
  src/components/OpenActivity.vue
Labels: enhancement, UI

#46 fix: tcx decode unexpected error due to improper HR parse handling
  src/wasm/activity-service/activity/tcx/record.go
  src/wasm/activity-service/activity/tcx/schema/activity.go
  src/wasm/activity-service/activity/tcx/schema/author.go
  src/wasm/activity-service/activity/tcx/schema/lap.go
  src/wasm/activity-service/activity/tcx/schema/tcx.go
  src/wasm/activity-service/activity/tcx/schema/track.go
Labels: WebAssembly

#47 feat: building block for encoding
  src/components/OpenActivity.vue
  src/spec/activity-service.ts
  src/wasm/activity-service/activity/fit/creator.go
  src/wasm/activity-service/activity/fit/manufacturer.go
  src/wasm/activity-service/activity/fit/service.go
  src/wasm/activity-service/activity/fit/session.go
  src/wasm/activity-service/activity/gpx/service.go
  src/wasm/activity-service/activity/tcx/service.go
  src/wasm/activity-service/activity/util.go
  src/wasm/activity-service/kit/kit.go
  src/wasm/activity-service/main.go
  src/wasm/activity-service/manufacturers.json
  src/wasm/activity-service/scale/scale.go
  src/wasm/activity-service/service/result.go
  src/wasm/activity-service/service/result/decode.go
  src/wasm/activity-service/service/result/encode.go
  src/wasm/activity-service/service/result/manufacturer-list.go
  src/wasm/activity-service/service/service.go
  src/workers/activity-service.ts
Labels: enhancement
